# Generated by Django 3.1.2 on 2020-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20201012_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='google',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
