# Generated by Django 3.1.2 on 2020-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_gallery_galleryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
